// <auto-generated />
using System;
using HRManagement.Web.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManagement.Web.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230615084401_ap")]
    partial class ap
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HRManagement.Web.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Street1")
                        .HasColumnType("longtext");

                    b.Property<string>("Street2")
                        .HasColumnType("longtext");

                    b.Property<string>("Street3")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = "B22699V4-42A2-4666-9631-1C2D1E2QE4F7",
                            City = "qWxdptf99V53m3HvJKwiyg==",
                            Street1 = "nrYvHAOpYT1icobLTkQ4XQ==",
                            Street2 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            Street3 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            ZipCode = "jT5NXNJs3hNAgncxRV5IJg=="
                        },
                        new
                        {
                            Id = "C44698B8-89A2-4115-9631-1C2D1E2AC5F7",
                            City = "qWxdptf99V53m3HvJKwiyg==",
                            Street1 = "YUOKTkjPIcCdp0RFv0M995E9FNrV4Yqf0AZO/w4K8VA=",
                            Street2 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            Street3 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            ZipCode = "fqv0JX8PgBMMSKadKO8wUA=="
                        },
                        new
                        {
                            Id = "D55699V4-42A2-4666-9631-1C2D1E2QE4F7",
                            City = "qWxdptf99V53m3HvJKwiyg==",
                            Street1 = "N8SZmdEorA16bD1D14eQgA==",
                            Street2 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            Street3 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            ZipCode = "jT5NXNJs3hNAgncxRV5IJg=="
                        },
                        new
                        {
                            Id = "E66698B8-89A2-4115-9631-1C2D1E2AC5F7",
                            City = "cC5WEXQrlF8DxQZ5INUEcQ==",
                            Street1 = "4nL/FfFSsPNEECz4eSRT8ENay+dNU7kUoTZxBrlniPE=",
                            Street2 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            Street3 = "UhTX5ZpJ4y2iv3Vcblzqvw==",
                            ZipCode = "fqv0JX8PgBMMSKadKO8wUA=="
                        });
                });

            modelBuilder.Entity("HRManagement.Web.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = "B22699V4-42A2-4666-9631-1D9D1E2QE4F7",
                            Description = "DESC CLIENT1",
                            Name = "CLIENT1"
                        },
                        new
                        {
                            Id = "C4469D48-89A2-3615-9631-1C2D1E2AC/&7",
                            Description = "DESC CLIENT2",
                            Name = "CLIENT2"
                        });
                });

            modelBuilder.Entity("HRManagement.Web.Models.Diploma", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("Date");

                    b.Property<string>("Libelle")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Diplomas");

                    b.HasData(
                        new
                        {
                            Id = "B123V455-42A2-3456-9631-1DHZSE2QE4F7",
                            EndDate = new DateTime(2015, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "E7HAk0sSrG5MNlEhSSXbxg==",
                            StartDate = new DateTime(2017, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "E22678B8-42A2-4115-9631-1CE51E2AC5F7"
                        },
                        new
                        {
                            Id = "C4469D48-89A2-3615-9631-1C2D1E2AC2&7",
                            EndDate = new DateTime(2009, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "FE4M/Q+DQs2gVsq8mNFgZb2mENKClUVBSW1T8OM6MHw=",
                            StartDate = new DateTime(2011, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "E22678B8-42A2-4115-9631-1CE51E2AC5F7"
                        },
                        new
                        {
                            Id = "C4H83D48-89A2-3615-9631-1C2DAL0AC9&7",
                            EndDate = new DateTime(2013, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "ktJ4K+MXoJcFcwftaKi7Wg==",
                            StartDate = new DateTime(2016, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "B22698B8-42A2-4115-9631-1C2D1E2AC5F7"
                        });
                });

            modelBuilder.Entity("HRManagement.Web.Models.DiplomaSkill", b =>
                {
                    b.Property<string>("DiplomaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SkillId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("DiplomaId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("DiplomaSkills");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Mission", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("MissionEnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("HRManagement.Web.Models.MissionSkill", b =>
                {
                    b.Property<string>("MissionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SkillId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("MissionId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("MissionSkills");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("Date");

                    b.Property<string>("Libelle")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectEnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HRManagement.Web.Models.School", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("Date");

                    b.Property<string>("Libelle")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = "B123V455-42A2-3456-9631-1DHZSE2QE4F7",
                            EndDate = new DateTime(2013, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "q8ieydXLnJMphy5L4wp76A==",
                            StartDate = new DateTime(2016, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "E22678B8-42A2-4115-9631-1CE51E2AC5F7"
                        },
                        new
                        {
                            Id = "C4469D48-89A2-3615-9631-1C2D1E2AC2&7",
                            EndDate = new DateTime(2013, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Pet7i993BgS+uQZJeQYSVQ==",
                            StartDate = new DateTime(2016, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "E22678B8-42A2-4115-9631-1CE51E2AC5F7"
                        },
                        new
                        {
                            Id = "C4H83D48-89A2-3615-9631-1C2DAL0AC9&7",
                            EndDate = new DateTime(2013, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "b+8rJ0ACwlqFzv48DSeleVeJCjkXxP9RxmDOTM5cfLc=",
                            StartDate = new DateTime(2016, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "B22698B8-42A2-4115-9631-1C2D1E2AC5F7"
                        });
                });

            modelBuilder.Entity("HRManagement.Web.Models.Skill", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Libelle")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = "B22699V4-42A2-4666-9631-1C2D1E2QE4F7",
                            Description = "Lorem ispum",
                            Libelle = "Python"
                        },
                        new
                        {
                            Id = "C44698B8-89A2-4115-9631-1C2D1E2AC5F7",
                            Description = "Lorem ispum",
                            Libelle = "Java"
                        },
                        new
                        {
                            Id = "D55699V4-42A2-4666-9631-1C2D1E2QE4F7",
                            Description = "Lorem ispum",
                            Libelle = "C#"
                        },
                        new
                        {
                            Id = "E66698B8-89A2-4115-9631-1C2D1E2AC5F7",
                            Description = "Lorem ispum",
                            Libelle = "PHP"
                        },
                        new
                        {
                            Id = "E87658B8-89A2-4115-9631-1C2D1E2AC5F7",
                            Description = "Lorem ispum",
                            Libelle = "NodeJS"
                        });
                });

            modelBuilder.Entity("HRManagement.Web.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AddressId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BirthCountry")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("longtext");

                    b.Property<float>("BrutSalary")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NatCardNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.Property<float>("NetSalary")
                        .HasColumnType("float");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PositionEnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecCardNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "B22698B8-42A2-4115-9631-1C2D1E2AC5F7",
                            AccessFailedCount = 0,
                            AddressId = "B22699V4-42A2-4666-9631-1C2D1E2QE4F7",
                            BirthCountry = "JQA8CV5rxSF0/Hp6+X36Ww==",
                            BirthDate = new DateTime(1996, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "jLy3HqDCK0+/NECBgw3iQA==",
                            BrutSalary = 0f,
                            ConcurrencyStamp = "836ad91b-bbe8-4949-b42b-35030f5a2fdd",
                            Email = "admin1@admin.fr",
                            EmailConfirmed = true,
                            FirstName = "/Jd2bzeOttDTlAepi7Vj7Q==",
                            LastName = "HarYCrqDtXq0aGL4Euy0Zw==",
                            LockoutEnabled = false,
                            NatCardNumber = "lPfqw/4To4cUqkFXmjr99A==",
                            Nationality = "/JPYnJI6bQjl6aZqqg748Q==",
                            NetSalary = 0f,
                            NormalizedEmail = "ADMIN1@ADMIN.FR",
                            NormalizedUserName = "ADMIN1@ADMIN.FR",
                            PasswordHash = "AQAAAAEAACcQAAAAEEDSQxGwirlmjGvb87GqEgEq0qECAUxnYt57+yeui+aqcohm6Q3wEsGagXafNQdczg==",
                            PhoneNumberConfirmed = true,
                            PositionEnum = "MANAGER",
                            SecCardNumber = "RKni2nEve0sgoL7KKwYx5A==",
                            SecurityStamp = "943ccd6f-e18f-411e-aec8-c5d6af7900aa",
                            TwoFactorEnabled = false,
                            UserName = "Admin1"
                        },
                        new
                        {
                            Id = "E22678B8-42A2-4115-9631-1CE51E2AC5F7",
                            AccessFailedCount = 0,
                            AddressId = "C44698B8-89A2-4115-9631-1C2D1E2AC5F7",
                            BirthCountry = "JQA8CV5rxSF0/Hp6+X36Ww==",
                            BirthDate = new DateTime(1986, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "jLy3HqDCK0+/NECBgw3iQA==",
                            BrutSalary = 0f,
                            ConcurrencyStamp = "5860acb3-6a2d-452e-99f8-92961cd5214c",
                            Email = "emp2@emp.fr",
                            EmailConfirmed = true,
                            FirstName = "X+XAHEIv6iQhza/ISyly4w==",
                            LastName = "RsGU0ra9qNyUFez5reZDig==",
                            LockoutEnabled = false,
                            NatCardNumber = "lPfqw/4To4cUqkFXmjr99A==",
                            Nationality = "/JPYnJI6bQjl6aZqqg748Q==",
                            NetSalary = 0f,
                            NormalizedEmail = "EMP2@EMP.FR",
                            NormalizedUserName = "EMP2@EMP.FR",
                            PasswordHash = "AQAAAAEAACcQAAAAEOHDHKW9UKnMvFQxsKdPB1H/gYPllZhCg1bqpdErcA6bRXx1v+vC3oUb2V0dsjE4fg==",
                            PhoneNumberConfirmed = true,
                            PositionEnum = "MANAGER",
                            SecCardNumber = "RKni2nEve0sgoL7KKwYx5A==",
                            SecurityStamp = "90784aed-fdb7-49e4-bc50-713be4fe6ed5",
                            TwoFactorEnabled = false,
                            UserName = "Emp2"
                        },
                        new
                        {
                            Id = "F33678B8-4G62-4115-9631-1CE51E2AC5F7",
                            AccessFailedCount = 0,
                            AddressId = "D55699V4-42A2-4666-9631-1C2D1E2QE4F7",
                            BirthCountry = "JQA8CV5rxSF0/Hp6+X36Ww==",
                            BirthDate = new DateTime(1990, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "ScRQbVozn+lzAJOs41qD0g==",
                            BrutSalary = 0f,
                            ConcurrencyStamp = "1f5b870e-808e-4704-aaa8-9f1bdca1bb6d",
                            Email = "emp3@emp.fr",
                            EmailConfirmed = true,
                            FirstName = "XPm7I7D6QN8s2mq8hyy/sg==",
                            LastName = "RsGU0ra9qNyUFez5reZDig==",
                            LockoutEnabled = false,
                            NatCardNumber = "lPfqw/4To4cUqkFXmjr99A==",
                            Nationality = "/JPYnJI6bQjl6aZqqg748Q==",
                            NetSalary = 0f,
                            NormalizedEmail = "EMP3@EMP.FR",
                            NormalizedUserName = "EMP3@EMP.FR",
                            PasswordHash = "AQAAAAEAACcQAAAAEHncxwwmEyO8ryEsqZcG5cdrWXNH0Z2zr7pMlVQBvwI9aocHq5L8FzRmybIQixm8TA==",
                            PhoneNumberConfirmed = true,
                            PositionEnum = "MANAGER",
                            SecCardNumber = "RKni2nEve0sgoL7KKwYx5A==",
                            SecurityStamp = "0cdda8bf-5478-4450-a04e-cead4459635b",
                            TwoFactorEnabled = false,
                            UserName = "Emp3"
                        },
                        new
                        {
                            Id = "C55678B8-4209-4115-9631-1CE51E2AC5F7",
                            AccessFailedCount = 0,
                            AddressId = "E66698B8-89A2-4115-9631-1C2D1E2AC5F7",
                            BirthCountry = "JQA8CV5rxSF0/Hp6+X36Ww==",
                            BirthDate = new DateTime(1975, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "g+PoCWm3amX+lswFWV8cAA==",
                            BrutSalary = 0f,
                            ConcurrencyStamp = "6d9c64b3-0b3c-44d8-bb8a-da03e68b9684",
                            Email = "emp4@emp.fr",
                            EmailConfirmed = true,
                            FirstName = "/D2ZmG3Ut4D7HZnQ4LIC3A==",
                            LastName = "9KxG3ftafKogzxBycgaaqw==",
                            LockoutEnabled = false,
                            NatCardNumber = "lPfqw/4To4cUqkFXmjr99A==",
                            Nationality = "/JPYnJI6bQjl6aZqqg748Q==",
                            NetSalary = 0f,
                            NormalizedEmail = "EMP4@EMP.FR",
                            NormalizedUserName = "EMP4@EMP.FR",
                            PasswordHash = "AQAAAAEAACcQAAAAEDkoWoqd+7DSDDoKudy1pxjZKd6R2YPZaXhkmdiHGYHDuycsIaUnKNtGyZcPdthNAQ==",
                            PhoneNumberConfirmed = true,
                            PositionEnum = "MANAGER",
                            SecCardNumber = "RKni2nEve0sgoL7KKwYx5A==",
                            SecurityStamp = "b5b9254f-0c84-4822-86d6-862eab628822",
                            TwoFactorEnabled = false,
                            UserName = "Emp4"
                        });
                });

            modelBuilder.Entity("HRManagement.Web.Models.UserProject", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7D9B7113-A8F8-4035-99A7-A20DD400F6A3",
                            ConcurrencyStamp = "661e5a96-59fa-4ecb-8ac6-ba77545409f4",
                            Name = "Employe",
                            NormalizedName = "EMPLOYE"
                        },
                        new
                        {
                            Id = "2301D884-221A-4E7D-B509-0113DCC043E1",
                            ConcurrencyStamp = "b551c7e5-651a-40e2-9997-40073cfba895",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "B22698B8-42A2-4115-9631-1C2D1E2AC5F7",
                            RoleId = "2301D884-221A-4E7D-B509-0113DCC043E1"
                        },
                        new
                        {
                            UserId = "E22678B8-42A2-4115-9631-1CE51E2AC5F7",
                            RoleId = "7D9B7113-A8F8-4035-99A7-A20DD400F6A3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRManagement.Web.Models.Diploma", b =>
                {
                    b.HasOne("HRManagement.Web.Models.User", "User")
                        .WithMany("Diplomas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Web.Models.DiplomaSkill", b =>
                {
                    b.HasOne("HRManagement.Web.Models.Diploma", "Diploma")
                        .WithMany("DiplomaSkills")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagement.Web.Models.Skill", "Skill")
                        .WithMany("DiplomaSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diploma");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Mission", b =>
                {
                    b.HasOne("HRManagement.Web.Models.Project", "Project")
                        .WithMany("Missios")
                        .HasForeignKey("ProjectId");

                    b.HasOne("HRManagement.Web.Models.User", "User")
                        .WithMany("Missions")
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Web.Models.MissionSkill", b =>
                {
                    b.HasOne("HRManagement.Web.Models.Mission", "Mission")
                        .WithMany("MissionSkills")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagement.Web.Models.Skill", "Skill")
                        .WithMany("MissionSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Project", b =>
                {
                    b.HasOne("HRManagement.Web.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HRManagement.Web.Models.School", b =>
                {
                    b.HasOne("HRManagement.Web.Models.User", "User")
                        .WithMany("Schools")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Web.Models.User", b =>
                {
                    b.HasOne("HRManagement.Web.Models.Address", "Address")
                        .WithOne("User")
                        .HasForeignKey("HRManagement.Web.Models.User", "AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("HRManagement.Web.Models.UserProject", b =>
                {
                    b.HasOne("HRManagement.Web.Models.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagement.Web.Models.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HRManagement.Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HRManagement.Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagement.Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HRManagement.Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRManagement.Web.Models.Address", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Diploma", b =>
                {
                    b.Navigation("DiplomaSkills");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Mission", b =>
                {
                    b.Navigation("MissionSkills");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Project", b =>
                {
                    b.Navigation("Missios");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("HRManagement.Web.Models.Skill", b =>
                {
                    b.Navigation("DiplomaSkills");

                    b.Navigation("MissionSkills");
                });

            modelBuilder.Entity("HRManagement.Web.Models.User", b =>
                {
                    b.Navigation("Diplomas");

                    b.Navigation("Missions");

                    b.Navigation("Schools");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
