var namespace_asp_net_core =
[
    [ "Views__ViewImports", "class_asp_net_core_1_1_views_____view_imports.html", "class_asp_net_core_1_1_views_____view_imports" ],
    [ "Views__ViewStart", "class_asp_net_core_1_1_views_____view_start.html", "class_asp_net_core_1_1_views_____view_start" ],
    [ "Views_Account_AccessDenied", "class_asp_net_core_1_1_views___account___access_denied.html", "class_asp_net_core_1_1_views___account___access_denied" ],
    [ "Views_Account_ConfirmEmail", "class_asp_net_core_1_1_views___account___confirm_email.html", "class_asp_net_core_1_1_views___account___confirm_email" ],
    [ "Views_Account_Edit", "class_asp_net_core_1_1_views___account___edit.html", "class_asp_net_core_1_1_views___account___edit" ],
    [ "Views_Account_Error", "class_asp_net_core_1_1_views___account___error.html", "class_asp_net_core_1_1_views___account___error" ],
    [ "Views_Account_Login", "class_asp_net_core_1_1_views___account___login.html", "class_asp_net_core_1_1_views___account___login" ],
    [ "Views_Account_Register", "class_asp_net_core_1_1_views___account___register.html", "class_asp_net_core_1_1_views___account___register" ],
    [ "Views_Account_SuccessRegistration", "class_asp_net_core_1_1_views___account___success_registration.html", "class_asp_net_core_1_1_views___account___success_registration" ],
    [ "Views_Client_Add", "class_asp_net_core_1_1_views___client___add.html", "class_asp_net_core_1_1_views___client___add" ],
    [ "Views_Client_Edit", "class_asp_net_core_1_1_views___client___edit.html", "class_asp_net_core_1_1_views___client___edit" ],
    [ "Views_Dashboard_Index", "class_asp_net_core_1_1_views___dashboard___index.html", "class_asp_net_core_1_1_views___dashboard___index" ],
    [ "Views_Emails_EmailRegisterTemplate", "class_asp_net_core_1_1_views___emails___email_register_template.html", "class_asp_net_core_1_1_views___emails___email_register_template" ],
    [ "Views_Home_Index", "class_asp_net_core_1_1_views___home___index.html", "class_asp_net_core_1_1_views___home___index" ],
    [ "Views_Home_Privacy", "class_asp_net_core_1_1_views___home___privacy.html", "class_asp_net_core_1_1_views___home___privacy" ],
    [ "Views_Mission_Add", "class_asp_net_core_1_1_views___mission___add.html", "class_asp_net_core_1_1_views___mission___add" ],
    [ "Views_Mission_Edit", "class_asp_net_core_1_1_views___mission___edit.html", "class_asp_net_core_1_1_views___mission___edit" ],
    [ "Views_Project__UserEditor", "class_asp_net_core_1_1_views___project_____user_editor.html", "class_asp_net_core_1_1_views___project_____user_editor" ],
    [ "Views_Project_Add", "class_asp_net_core_1_1_views___project___add.html", "class_asp_net_core_1_1_views___project___add" ],
    [ "Views_Project_Edit", "class_asp_net_core_1_1_views___project___edit.html", "class_asp_net_core_1_1_views___project___edit" ],
    [ "Views_Project_GetProject", "class_asp_net_core_1_1_views___project___get_project.html", "class_asp_net_core_1_1_views___project___get_project" ],
    [ "Views_Shared__Clients", "class_asp_net_core_1_1_views___shared_____clients.html", "class_asp_net_core_1_1_views___shared_____clients" ],
    [ "Views_Shared__Layout", "class_asp_net_core_1_1_views___shared_____layout.html", "class_asp_net_core_1_1_views___shared_____layout" ],
    [ "Views_Shared__Missions", "class_asp_net_core_1_1_views___shared_____missions.html", "class_asp_net_core_1_1_views___shared_____missions" ],
    [ "Views_Shared__MissionsByUser", "class_asp_net_core_1_1_views___shared_____missions_by_user.html", "class_asp_net_core_1_1_views___shared_____missions_by_user" ],
    [ "Views_Shared__Projects", "class_asp_net_core_1_1_views___shared_____projects.html", "class_asp_net_core_1_1_views___shared_____projects" ],
    [ "Views_Shared__ProjectsByUser", "class_asp_net_core_1_1_views___shared_____projects_by_user.html", "class_asp_net_core_1_1_views___shared_____projects_by_user" ],
    [ "Views_Shared__StatusMessage", "class_asp_net_core_1_1_views___shared_____status_message.html", "class_asp_net_core_1_1_views___shared_____status_message" ],
    [ "Views_Shared__Users", "class_asp_net_core_1_1_views___shared_____users.html", "class_asp_net_core_1_1_views___shared_____users" ],
    [ "Views_Shared__ValidationScriptsPartial", "class_asp_net_core_1_1_views___shared_____validation_scripts_partial.html", "class_asp_net_core_1_1_views___shared_____validation_scripts_partial" ],
    [ "Views_Shared_Error", "class_asp_net_core_1_1_views___shared___error.html", "class_asp_net_core_1_1_views___shared___error" ],
    [ "Views_User_GetUser", "class_asp_net_core_1_1_views___user___get_user.html", "class_asp_net_core_1_1_views___user___get_user" ]
];