var namespace_h_r_management_1_1_web_1_1_custom_token_providers =
[
    [ "EmailConfirmationTokenProvider", "class_h_r_management_1_1_web_1_1_custom_token_providers_1_1_email_confirmation_token_provider.html", "class_h_r_management_1_1_web_1_1_custom_token_providers_1_1_email_confirmation_token_provider" ],
    [ "EmailConfirmationTokenProviderOptions", "class_h_r_management_1_1_web_1_1_custom_token_providers_1_1_email_confirmation_token_provider_options.html", null ]
];